### PR TITLE
NVIDIA Mig support

### LINKED ISSUE #1198: GPU NVIDIA H100 PCIe not supported
### What happened?

I've deployed Kepler on a Kubernetes to monitor a cluster with a GPU node with a NIVIDIA H100 PCIe.

In the kepler logs from this node, I've this error. In parallel I'm monitoring this GPU with a dgcm-exporter instance and it can collect gpu energy consumption metrics correctly.

I0125 07:04:48.972351 1 power.go:86] Failed to collect GPU metrics, trying to initizalize again: failed to get processes' utilization on device {0x7f639b40bdf8}: Not Supported
I0125 07:04:48.972407 1 gpu_nvml.go:62] found 1 gpu devices
I0125 07:04:48.972416 1 gpu_nvml.go:73] GPU 0 NVIDIA H100 PCIe

Do you have an idea ?

### What did you expect to happen?

Collect metrics from NVIDIA H100 PCIe

### How can we reproduce it (as minimally and precisely as possible)?

Run a Kepler instance on a device with a NVIDIA H100 PCIe

### Anything else we need to know?

_No response_

### Kepler image tag

<details>

</details>

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.2", GitCommit:"89a4ea3e1e4ddd7f7572286090359983e0387b2f", GitTreeState:"clean", BuildDate:"2023-09-13T09:29:07Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider or bare metal

<details>
Scaleway Kapsule cluster
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Kepler deployment config

<details>

For on kubernetes:
```console
$ KEPLER_NAMESPACE=kepler

# provide kepler configmap
$ kubectl get configmap kepler-cfm -n ${KEPLER_NAMESPACE} 
# paste output here

# provide kepler deployment description
$ kubectl describe deployment kepler-exporter -n ${KEPLER_NAMESPACE} 
```

For standalone:
# put your Kepler command argument here

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by rootfs**
fix #1198 

# Test status
I am running a text generation inference pod and the measured power
## Load generation
`kubectl exec` to the `text-generation-inference` pod, and run the command to generate text and pause 5 seconds after each run:
```bash
# while true; do curl localhost:8080/generate -X POST -H "Content-Type: application/json" -d '{"inputs": "<s>[INST] Write a K8s YAML file to create a pod that deploys nginx[/INST]", "parameters": {"max_new_tokens": 400}}';sleep 5;done
```
## Test result
```console
# nvidia-smi
+---------------------------------------------------------------------------------------+
| MIG devices:                                                                          |
+------------------+--------------------------------+-----------+-----------------------+
| GPU  GI  CI  MIG |                   Memory-Usage |        Vol|      Shared           |
|      ID  ID  Dev |                     BAR1-Usage | SM     Unc| CE ENC DEC OFA JPG|
|                  |                                |        ECC|                       |
|==================+================================+===========+=======================|
|  1    2   0   0  |           18816MiB / 19968MiB  | 42      0 |  3   0    2    0    0 |
|                  |               2MiB / 32767MiB  |           |                       |
+------------------+--------------------------------+-----------+-----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    1    2    0     494327      C   /opt/conda/bin/python3.9                  18770MiB |
+---------------------------------------------------------------------------------------+
```

image

# Method

The current way of process energy in MIG device is as the following:
- Get the MIG multi processor unit ratio with respect to the GPU, noted as `multiprocessorCountRatio` below. This is done via parsing `nvidia-smi -q -x` output
- Get the `DCGM_FI_PROF_PIPE_TENSOR_ACTIVE` counter from the MIG (thanks to @yuezhu1)
- Calculate the processor's smUtil = `multiprocessorCountRatio` * `DCGM_FI_PROF_PIPE_TENSOR_ACTIVE`

# TODO
- This PR uses mixed nvml (to get running processes) and dcgm to get info from different libraries. We should really use just one library (opened issue at go-dcgm).
- This PR doesn't address issues where the MIG can be dynamically reconfigured.
- We need to test more cases: no MIG, one MIG, multiple MIGs, processes running on 1+ MIGs, and processes running on MIG + GPU, etc

### CODE REVIEW

File: pkg/sensors/accelerator/gpu/source/gpu_dcgm.go [hunk 1]
```diff
@@ -0,0 +1,326 @@
...
+				entityName := gpuMigArray[deviceIndex][p.GpuInstanceId].EntityName
+				multiprocessorCountRatio := gpuMigArray[deviceIndex][p.GpuInstanceId].MultiprocessorCountRatio
+				mi := d.entities[entityName]
+				miVals, err = dcgm.EntityGetLatestValues(mi.EntityGroupId, mi.EntityId, deviceFields)
+				if err == nil {
+					for i, val := range miVals {
+						label := deviceFieldsString[i]
+						value := ToString(val)
+						klog.Infof("Device %v Label %v Val: %v", entityName, label, value)
+						if val.FieldId == dcgm.DCGM_FI_PROF_SM_ACTIVE {
```
Comment (yuezhu1) [inline pkg/sensors/accelerator/gpu/source/gpu_dcgm.go:254]: we can use `DCGM_FI_PROF_PIPE_TENSOR_ACTIVE` instead of `DCGM_FI_PROF_SM_ACTIVE` here, since `DCGM_FI_PROF_PIPE_TENSOR_ACTIVE` looks closer to actual  resource utilization rate

Comment (rootfs) [reply pkg/sensors/accelerator/gpu/source/gpu_dcgm.go]: updated

File: pkg/sensors/accelerator/gpu/source/gpu_dcgm.go [hunk 2]
```diff
@@ -0,0 +1,372 @@
...
+			miVals, err = dcgm.EntityGetLatestValues(mi.EntityGroupId, mi.EntityId, deviceFields)
+			if err == nil {
+				for i, val := range miVals {
+					label := deviceFieldsString[i]
+					value := ToString(val)
+					klog.V(debugLevel).Infof("Device %v Label %v Val: %v", entityName, label, value)
+					if val.FieldId == ratioFields {
+						floatVal, _ := strconv.ParseFloat(value, 32)
+						// ratio of active multiprocessors to total multiprocessors
+						smUtil := uint32(floatVal * 100 * multiprocessorCountRatio)
```
Comment (marceloamaral) [inline pkg/sensors/accelerator/gpu/source/gpu_dcgm.go:211]: This variable represents tensor core utilization, not SM utilization.

It might be better to just use "util" since the variable will hold the utilization of different components in the future.

File: pkg/sensors/accelerator/gpu/source/gpu_dcgm.go [hunk 3]
```diff
@@ -0,0 +1,372 @@
...
+						klog.V(debugLevel).Infof("pid %d smUtil %d multiprocessor count ratio %v\n", p.Pid, smUtil, multiprocessorCountRatio)
+						processAcceleratorMetrics[p.Pid] = ProcessUtilizationSample{
+							Pid:       p.Pid,
+							TimeStamp: uint64(time.Now().UnixNano()),
+							SmUtil:    smUtil,
```
Comment (marceloamaral) [inline pkg/sensors/accelerator/gpu/source/gpu_dcgm.go:216]: Same here.

File: pkg/collector/stats/stats.go [hunk 4]
```diff
@@ -75,7 +75,7 @@ func NewStats() *Stats {
 		m.ResourceUsage[metricName] = types.NewUInt64StatCollection()
 	}
 
-	if gpu.IsGPUCollectionSupported() {
+	if config.EnabledGPU {
```
Comment (marceloamaral) [inline pkg/collector/stats/stats.go:78]: Why not use `gpu.IsGPUCollectionSupported()`?
A user could enable GPU in Kepler configuration but the system might not have GPUs.

File: pkg/collector/resourceutilization/accelerator/process_gpu_collector.go [hunk 5]
```diff
@@ -78,8 +78,9 @@ func UpdateNodeGPUUtilizationMetrics(processStats map[uint64]*stats.ProcessStats
 				}
 				processStats[uintPid] = stats.NewProcessStats(uintPid, uint64(0), containerID, vmID, command)
 			}
-			processStats[uintPid].ResourceUsage[config.GPUSMUtilization].AddDeltaStat(utils.GenericSocketID, uint64(processUtilization.SmUtil))
-			processStats[uintPid].ResourceUsage[config.GPUMemUtilization].AddDeltaStat(utils.GenericSocketID, uint64(processUtilization.MemUtil))
+			gpuName := fmt.Sprintf("%s%v", utils.GenericGPUID, gpuID)
```
Comment (marceloamaral) [inline pkg/collector/resourceutilization/accelerator/process_gpu_collector.go:81]: @rootfs how did this solve the GPU MIG naming problem?
You are also using the GPU ID as the key as in the PR #1236.
Note that the `utils.GenericGPUID` will be the same for all MIG instance, so in the end, this is doing the same thing as in the PR #1236.

Also, note that the PR #1236 is fixing other things :)

File: pkg/sensors/accelerator/gpu/source/gpu_dcgm.go [hunk 6]
```diff
@@ -0,0 +1,372 @@
...
+	if strErr != nil {
+		klog.V(debugLevel).Infof("failed to convert %q to an integer: %v", deviceName, strErr)
+		return processAcceleratorMetrics, strErr
+	}
+	vals, err = dcgm.GetLatestValuesForFields(uint(deviceIndex), deviceFields)
+	if err != nil {
+		klog.V(debugLevel).Infof("failed to get latest values for fields: %v", err)
+		return processAcceleratorMetrics, err
+	}
+	gpuSMActive := uint32(0)
```
Comment (marceloamaral) [inline pkg/sensors/accelerator/gpu/source/gpu_dcgm.go:178]: Same here, this is tensor utilization, not SM.
It might be better to just use `utilization`.

**Comment by rootfs** [comment]
@marceloamaral review addressed

File: pkg/sensors/accelerator/gpu/source/gpu_dcgm.go [hunk 7]
```diff
@@ -0,0 +1,389 @@
...
+func (d *GPUDcgm) GetName() string {
+	return "dcgm"
+}
+
+func (d *GPUDcgm) InitLib() error {
+	d.devices = make(map[string]interface{})
+	d.entities = make(map[string]dcgm.GroupEntityPair)
+
+	// cleanup, err := dcgm.Init(dcgm.Embedded) // embeded mode is not recommended for production per https://github.com/NVIDIA/dcgm-exporter/issues/22#issuecomment-1321521995
+	cleanup, err := dcgm.Init(dcgm.Standalone, config.DCGMHostEngineEndpoint, "0")
```
Comment (rootfs) [inline pkg/sensors/accelerator/gpu/source/gpu_dcgm.go:75]: this requires :
- the host must enable dcgm service and run nv-hostengine
- pod spec to enable `hostNetwork` so to access the nvidia dcgm hostengine

Comment (rootfs) [reply pkg/sensors/accelerator/gpu/source/gpu_dcgm.go:75]: To investigate how to use `embeded` mode after this PR is merged.

**Comment by rootfs** [comment]
A test image is built `quay.io/sustainable_computing_io/kepler:latest-dcgm`

File: pkg/sensors/accelerator/gpu/source/gpu_dcgm.go (hunk 7 above)
Comment (marceloamaral) [reply pkg/sensors/accelerator/gpu/source/gpu_dcgm.go:75]: I forgot to mention that, the `standalone` connecting to the localhost works in K8s environments.

**Review by marceloamaral — APPROVED** [review]
/lgtm

File: pkg/sensors/accelerator/gpu/source/gpu_dcgm.go (hunk 7 above)
Comment (rootfs) [reply pkg/sensors/accelerator/gpu/source/gpu_dcgm.go:75]: ok, let's consider it as an enhancement then.

Comment (rootfs) [reply pkg/sensors/accelerator/gpu/source/gpu_dcgm.go:75]: here is the issue https://github.com/sustainable-computing-io/kepler/issues/1243
