### PR TITLE
detect kernel version through unix way

### LINKED ISSUE #179: getKernelVersion doesn't work at all
**Describe the bug**

https://github.com/sustainable-computing-io/kepler/blob/main/pkg/config/config.go#L65

paste those to https://go.dev/play/ and run it 
```
package main

import (
	"encoding/json"
	"fmt"

	"github.com/zcalusic/sysinfo"
)

func main() {

	var si sysinfo.SysInfo

	si.GetSysInfo()

	data, err := json.MarshalIndent(&si, "", "  ")
	if err == nil {
		var result map[string]map[string]string
		if err = json.Unmarshal(data, &result); err != nil {
			fmt.Println("----")
			fmt.Println(err)
			fmt.Println("----")
		}
	}
	fmt.Println("done")
}

```

```
----
json: cannot unmarshal number into Go value of type string
----
done

```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by jichenjc**
Fixes #179

### CODE REVIEW

File: pkg/config/config.go [hunk 1]
```diff
@@ -17,12 +17,12 @@ limitations under the License.
 package config
 
 import (
-	"encoding/json"
+	"bytes"
 	"fmt"
 	"os"
 	"strconv"
 
-	"github.com/zcalusic/sysinfo"
```
Comment (rootfs) [inline pkg/config/config.go:25]: can you remove this pkg from go.mod and vendor too?

**Review by rootfs — APPROVED** [review]
