### PR TITLE
fix: search scope file update for not found issue

### LINKED ISSUE #352: VM: all node / pod energy report 0 (again..)
**Describe the bug**

after use latest update with a few enhancement, my pod/node report energy become 0 again.. 
switch to v0.3 I can see the data correctly reported ,...

latest
```
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0kepler_node_energy_stat{cpu_architecture="Haswell",node_block_devices_used="0",node_curr_bytes_read="0",node_curr_bytes_writes="0",node_curr_cache_miss="0",node_curr_container_cpu_usage_seconds_total="0",node_curr_container_memory_working_set_bytes="0",node_curr_cpu_cycles="0",node_curr_cpu_instr="0",node_curr_cpu_time="0",node_curr_energy_in_core_joule="0",node_curr_energy_in_dram_joule="0",node_curr_energy_in_gpu_joule="0",node_curr_energy_in_other_joule="0",node_curr_energy_in_pkg_joule="0",node_curr_energy_in_uncore_joule="0",node_name="jitest40"} 0

```
v0.3
```
# TYPE node_curr_energy_in_core_joule gauge
node_curr_energy_in_core_joule{instance="jitest40"} 0.026
# HELP node_curr_energy_in_dram_joule node_ current energy consumption in dram (joule)
# TYPE node_curr_energy_in_dram_joule gauge
node_curr_energy_in_dram_joule{instance="jitest40"} 0.708
# HELP node_curr_energy_in_gpu_joule node_ current energy consumption in gpu (joule)
# TYPE node_curr_energy_in_gpu_joule gauge
node_curr_energy_in_gpu_joule{instance="jitest40"} 0
# HELP node_curr_energy_in_other_joule node_ current energy consumption in other (joule)
# TYPE node_curr_energy_in_other_joule gauge
node_curr_energy_in_other_joule{instance="jitest40"} 0
# HELP node_curr_energy_in_pkg_joule node_ current energy consumption in pkg (joule)
# TYPE node_curr_energy_in_pkg_joule gauge
node_curr_energy_in_pkg_joule{instance="jitest40"} 0.026
# HELP node_curr_energy_in_uncore_joule node_ current energy consumption in uncore (joule)
# TYPE node_curr_energy_in_uncore_joule gauge
node_curr_energy_in_uncore_joule{instance="jitest40"} 0
# HELP node_curr_energy_joule node_ current energy consumption (joule)
# TYPE node_curr_energy_joule gauge
node_curr_energy_joule{instance="jitest40"} 0.026

```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by jichenjc**
fix #352 

Signed-off-by: jichenjc <jichenjc@cn.ibm.com>

### CODE REVIEW

File: pkg/cgroup/slice_handler.go [hunk 1]
```diff
@@ -143,11 +144,34 @@ func GetStandardStat(containerID string) map[string]interface{} {
...
+			}
+			return nil
+		})
+	if found != nil {
+		return found.Error()
+	}
+	return ""
+}
+
 func findContainerScope(path string) string {
```
Comment (marceloamaral) [inline pkg/cgroup/slice_handler.go:164]: Can you add a unit test for this?

**Review by marceloamaral — APPROVED** [review]
/lgtm
